### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by forrestzhang** [libnano/primer3-py#12]
I am trying to install primer3-py, I got this error:

```
Traceback (most recent call last):
  File "setup.py", line 53, in <module>
    LONG_DESCRIPTION = fd.read()
  File "/usr/local/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1271: ordinal not in range(128)

```

**Comment by benpruitt** [comment]
It looks like README.rst contains a non-ASCII character (the "micro" symbol, "µ"), so this problem will arise if the default encoding of your python framework is ASCII rather than utf-8. We will address this in a future release, but for now you should be able to fix this by one of the two following methods:

1) remove the 'µ' symbol in README.rst before building
2) add the following lines to the top of setup.py
    #!/usr/bin/env python
    # -*- coding: utf-8 -*-
