### ISSUE TITLE
Salt correction params ignored in hairpin,etc calcs 

### ISSUE THREAD

**Issue by martinfthomsen** [libnano/primer3-py#21]
Hi Primer3-py,

According to the following post, the methods: calcHeterodimer, calcHairpin, etc. should be able to use the tm_method and salt_correction_method, is that something you could make primer3-py support as well?
https://sourceforge.net/p/primer3/feature-requests/25/

Here is a code example showing the issue:

    >>> primer3.thermoanalysis.ThermoAnalysis(salt_correction_method=0).calcHeterodimer('TGAGGCACCTATCTCAGCGA','TCGCTGAGATAGGTGCCTCA').tm
    62.99575324661981
    >>> primer3.thermoanalysis.ThermoAnalysis(salt_correction_method=1).calcHeterodimer('TGAGGCACCTATCTCAGCGA','TCGCTGAGATAGGTGCCTCA').tm
    62.99575324661981
    >>> primer3.thermoanalysis.ThermoAnalysis(salt_correction_method=0).calcTm('TGAGGCACCTATCTCAGCGA')
    59.81988509331603
    >>> primer3.thermoanalysis.ThermoAnalysis(salt_correction_method=1).calcTm('TGAGGCACCTATCTCAGCGA')
    63.07165934075988

As you can see, for the hetero dimer calculations, the salt_correction_method has no influence.

Best, Martin

**Comment by benpruitt** [comment]
I think that post was just referring to the salt correction parameters (i.e., monovalent cation concentration, divalent cation concentration, etc) rather than the tm / salt correction _methods_. There is no reference to the method used to calculate tm or salt corrections in thal.c/h, which is the piece of the primer3 code responsible for the heterodimer / homodimer / hairpin calculations. It appears that those parameters only apply to tm calculation (calcTm) which is instrumented in oligotm.c/h. You could reach out to the primer3 team for further clarification, but from what I can tell the current primer3 library does not support specifying the salt correction method or tm calculation method for the heterodimer / homodimer / hairpin calculations.

**Comment by martinfthomsen** [comment]
You are correct, I miss read, sorry.
