### ISSUE TITLE
python crash in libprimer3

### ISSUE THREAD

**Issue by mikheyev** [libnano/primer3-py#29]
Hi,

I am running several thousand primer designs and occasionally python crashes with the following error message `probably primer3_core:/private/var/folders/pg/kkbvf3d57y9fzbcff5n125_00000gn/T/pip-install-gJjJf3/primer3-py/primer3/src/libprimer3/libprimer3.c:5275, assertion (len >= 3) failed`

Weirdly, it seems to happen at the same time during the script that loops over the sites for which primers need to be designed, but if I run the code just for the site that has failed, it works.

Weirdly, at 5275 the check is for codon-specific primer designs, by I am using `'PRIMER_TASK': "pick_primer_list"`, so that section should never be executed.

Any ideas would be appreciated.

Sasha

**Comment by benpruitt** [comment]
Hi Sasha, that does seem strange. If the problem is easily reproducible, can you try running the `designPrimers` wrapper function (in lieu of the `designPrimers` binding-based function)? If you have a script you'd probably just need to substitute the import (i.e., replace `from primer3.bindings import designPrimers` with `from primer3.wrappers import designPrimers`). This will allow us to more easily determine if the issue arises from the primer3 C library or the binding that we wrote into it. 

It looks like the failed assertion that you're seeing is evaluated regardless of whether or not a codon check is required. `set_retval_both_stop_codons` is [called](https://github.com/libnano/primer3-py/blob/master/primer3/src/libprimer3/libprimer3.c#L1278) in the top-level `find_primers` c function and it calls `find_stop_codon` [twice](https://github.com/libnano/primer3-py/blob/master/primer3/src/libprimer3/libprimer3.c#L5235). At first glance it looks like this assertion fails when the `trimmed_seq` (which is the `INCLUDED_REGION` of the sequence) is < 3 nt in length.

**Comment by mikheyev** [comment]
Hi Ben,

Sorry for the long response time. Where is the syntax for the wrappers? If I just change the import command, I get the following error:

```
Traceback (most recent call last):
  File "test.py", line 100, in <module>
    primersLeft = designPrimers({'SEQUENCE_ID': snp, 'SEQUENCE_TEMPLATE': regionLeft}, params)
  File "/usr/local/lib/python2.7/site-packages/primer3/wrappers.py", line 275, in designPrimers
    input_log.write(in_str)
AttributeError: 'dict' object has no attribute 'write'
```

**Comment by benpruitt** [comment]
I think you just need to combine the two parameter dictionaries you are passing in:

```
params.update(
    {'SEQUENCE_ID': snp, 'SEQUENCE_TEMPLATE': regionLeft}
)
designPrimers(params)
```

**Comment by benpruitt** [comment]
@mikheyev -- just trying to close the loop here: did the above solution end up working out for you?
