### ISSUE TITLE
Units for Gibbs Free Energy

### ISSUE THREAD

**Issue by nathanielschleif** [libnano/primer3-py#32]
Hello - quick question, what are the intended units for Gibbs Free Energy as generated by "calcHairpin"? I would assume kcal/mol, however when I try to get the hairpin energetics for "TGGTGTTACAATGCAGACGCAATACACT" it reports a value around -900, which seems impossibly large if that is indeed the units:
![Screenshot from 2019-07-16 15-50-48](https://user-images.githubusercontent.com/36996223/61328839-85749100-a7e1-11e9-9292-10ea503793c3.png)

Thank you for any clarification on this.

**Comment by benpruitt** [comment]
I believe the results reported by `calcHairpin` (in the original [primer3 library](https://github.com/libnano/primer3-py/blob/master/primer3/src/libprimer3/thal.c#L2857)) and [later exposed via primer3-py](https://github.com/libnano/primer3-py/blob/master/primer3/thermoanalysis.pyx#L155) are reported in units of `cal` rather than `kcal` (so this is `900.59 cal/mol` -> `-0.90059 kcal/mol`)
