### ISSUE TITLE
documents for ASCII representation of computed dimer and hairpin structures?

### ISSUE THREAD

**Issue by billzt** [libnano/primer3-py#35]
The v0.6.0 adds features of "ASCII representation of computed dimer and hairpin structures". However there's no documention, as https://libnano.github.io/primer3-py/ still stays at v0.5.5

**Comment by xguse** [comment]
This is still an issue. I would REALLY like to see this because the ascii depictions do not use alignment depictions that I am used to seeing for hairpins etc. I am used to seeing:

From the primer3 site: http://primer3.org/manual.html#inputOutputConventions
```
Dimers:
t: 7.8  dG: -1724  dH: -91400  dS: -289
  5' ACGCAAAGCACGCTCC-CGATC 3'
      ||   |||  |||   ||
3' CTAGCCC-TCGCACGAAACGCA 5'

Hairpins:
t: 36.4  dG: 42  dH: -22500  dS: -73
5' CGCAAAGCACGCT┐
            ||  │
        3' AGCCC┘
```


But this is what y'all use:
```
SEQ	---------//----\\-
STR	CGCAAAGCACGCTCCCGA
```

I get the GENERAL idea that you are saying that the CG forms h-bonds with the later CG. But what do SEQ/STR represent? What are all the dashes before and after the `//`/`\\`?

What does it all mean and how do I use it? Please document it!


@benpruitt this seems to have been your commit?

**Comment by benpruitt** [comment]
We just take the output generated by the `primer3` library and expose it via the Python bindings. You can see the style of ASCII representation in question referenced in [their docs here](http://primer3.org/manual.html#PRIMER_MAX_HAIRPIN_TH).

I'd suggest contacting the `primer3` team if you have questions related to the format of the ASCII representation. I believe the best way to get in touch with them at this point is [via GitHub](https://github.com/primer3-org/primer3).

FWIW I get the same ASCII output as you when using the vanilla `primer3` library (no Python bindings):

```
$ ./ntthal -s1 CGCAAAGCACGCTCCCGA -a HAIRPIN
Calculated thermodynamical parameters for dimer:	18	dS = -72.6824	dH = -22500	dG = 42.4555	t = 36.4159
SEQ	---------//----\\-
STR	CGCAAAGCACGCTCCCGA
```

This is what you would expect given that `primer3-py` is just bindings into the `primer3` C library. AFAIK, the `-` represents a base that is not predicted to participate in the hairpin structure, whereas the `/` and `\` represent the bases that are participating in the hairpin structure (i.e., the hyphens between the slashes form the loop of the hairpin).

**Comment by benpruitt** [comment]
We updated all of the links to the `primer3` documentation in the nascent `primer3-py` [v1.0.0 release](https://github.com/libnano/primer3-py/releases/tag/v1.0.0) -- we don't plan on duplicating documentation of `primer3` features so if their latest documentation is insufficient, I would recommend [opening an issue on their GitHub project](https://github.com/primer3-org/primer3/issues).
