### ISSUE TITLE
Mispriming library causes primer3-py to crash

### ISSUE THREAD

**Issue by danxfreeman** [libnano/primer3-py#52]
My `primer3-py` script crashes whenever I add a mispriming library.

```
from primer3 import bindings

seq = 'CTCAGAAGCAAGAAGGGATGATTTCAGTTCTGATATGACCATACAGACCACTCAGGGAAAAACCCACCATGGATGAGTTCCTTCTTGTCACTATGAAATAAACTATAAAGAGCGATTGCTATAAAGCATGGGTGGGGTCATTCTCAATATTTCTTTCTGTCAAGGTAATAAATCCCAAATTCATAAGCCCCTTCAGATAAGGTTAGATGCAGGCCCCTCACTAAGGTGAACCTGACCTTACTTCTACACCCTTCAATTGAGTGACCAAGGATTGATGAGAAATATCAAGTATTTCATAAATATTTATTTTCTAAATATACAACTATAGAAAAGTGAGGTGTAACATATAGCTTGGATGAAGGGTTAAAATGTTAAGTATCTCATTGAGAAAAATGTGTTTGACATTTTTACATTAGAACAACATAATGGAGCAATGCTCACGCTAAACTGGGAACACTAATGTGAACTCAACTTAAATATTTTCCCACTTCTGTCACTAACAGTGGACACAGCAGCAGCAGCAGCAGCAGCAGCAGGAGTAGTACTAATGCCCACCACAACTCTCCTGTACCCCTAAATGGCCAGACTTTGTCTCTAACAGTTTTCTCCACTTAAAGAAACAGGGGCTCTTTGGAAGGGTTGTCCTGAGTAGGGTAAAACAAATGGTTTAAGCCTGGAAGTTTCTTTTGTAACCAGAAAGCAAGGATGCTTTCTAGAATATCACAGGGTGGTTCTGGAAGGACTAAGAAGCTAGATTAAAGAGGTTTCCTCTGGTCAAGCTCTGAGATTTTGAATATCAAATAAGATTGATGGCTATAATCAATTAAAACACATGGAGTCTGTGAAGAGCTGTAAGTTCCTAATGAAGCTATGAAGAGAAAAGTTGATGTAAATGGCAAATGCGATAGGGTTTTATTTCATATTATTTTTAATGGCAGATTTATATATGGGTGATATTATTTCTTCTATTAAATATATGTTGGGTTATTAAGCATCGATAGGCACTTTTCTCTATCCTTGTAAGAAGGAAAGAGTG'

bindings.designPrimers(
    global_args = {
        'PRIMER_MIN_SIZE': 18,
        'PRIMER_OPT_SIZE': 24,
        'PRIMER_MAX_SIZE': 30
    },
    seq_args = {
        'SEQUENCE_TEMPLATE': seq,
        'SEQUENCE_TARGET': [500, len(seq) - 1000]
    },
    misprime_lib = {'HUMAN': 'GRCh37.p13.genome.fa'} # uncommenting this line causes python to crash
)
```

Error message when I run the code in Spyder:

```
/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/scripts/conda‑activate.sh: line 14: 71804 Abort trap: 6 $CONDA_ENV_PYTHON ‑m spyder_kernels.console ‑f $SPYDER_KERNEL_SPEC
```

Error message when I run the code in Terminal:

```
probably primer3_core:primer3/src/libprimer3/libprimer3.c:5876, assertion (((void *)0) != s) failed
Abort trap: 6
```

I downloaded the library from ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_19/GRCh37.p13.genome.fa.gz

**Comment by danxfreeman** [comment]
Replacing `'GRCh37.p13.genome.fa'` with a sequence string does not produce an error

**Comment by benpruitt** [comment]
Hey Dan -- `bindings.designPrimers` expects `misprime_lib` to be a `dict` with the format `{<sequence name>: <sequence>}`, which `sequence` is the actual nucleotide sequence of the mispriming library member (see [docstring](https://github.com/libnano/primer3-py/blob/355b8b5a08a1e75648efe98bc9d2f8a3ec2514e8/primer3/bindings.py#L263)). This differs from the `primer3` binary API which does expect the `FASTA` file path as the value in the `dict`. 

We decided to structure the `bindings` API in this manner as it is directed more toward in memory design workflows rather than file-based workflows (so in your use case, you could use something like `Biopython` to first parse the FASTA into the appropriate `dict` format and then pass it to `bindings.designPrimers` as the mispriming library). 

With all of that being said, there _is_ a bug in one of our helper libraries that we'll address in the next release (which is triggering the abort trap rather than outputting the expected warning -- the `primer3` library is seeing `GRCh37.p13.genome.fa` as a nucleotide sequence and trying to print a warning that `3` is not a valid base identity). 

I'll leave this issue open until we fix the bug, but for now you should be good to go if you just change the format of your `misprime_lib` arg.

**Comment by danxfreeman** [comment]
Hi Ben, thanks for the tip. I poked around and saw the API actually uses a library of common repeats rather than the whole genome. I updated my Python script to download their library directly from GitHub.

```
url = 'https://raw.githubusercontent.com/primer3-org/primer3/main/src/humrep_and_simple.txt'
response = requests.get(url).text
fasta = SeqIO.parse(StringIO(response),'fasta')
misprime_lib = {rec.id: rec.seq for rec in fasta}
```
